### ISSUE TITLE
[BUG] Plugin not working

### ISSUE THREAD

**Issue by igorfrag** [noam09/deluge-telegramer#27]
**Describe the bug**
After installing the plugin ( both stable and alpha release tried), the plugin shows in the deluge interface but does not work at all. 

**To Reproduce**
1. Install the egg plugin via deluge interface.
2. Restart deluge after install, and fill all settings (API key, user id)
3. Nothing happens
4. See errors on logs.

**Expected behavior**
Receiving a test message after setting the plugin up, also my API key and user id is valid as i tested with another application.

**Logs**
[ERROR   ] 14:27:31 __init__:57 Appending to sys.path: 'c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg/telegramer/include'
[ERROR   ] 14:27:31 request:38 No module named certifi
Traceback (most recent call last):
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 36, in <module>
    import certifi
ImportError: No module named certifi

[ERROR   ] 14:27:33 __init__:57 Appending to sys.path: 'c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg/telegramer/include'

(deluge:14984): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(deluge:14984): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(deluge:14984): libglade-WARNING **: unknown attribute `swapped' for <signal>.
[ERROR   ] 14:27:33 __init__:57 Appending to sys.path: 'c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg/telegramer/include'
[ERROR   ] 14:27:33 updater:396 error in bootstrap phase; try=0 max_retries=0
Traceback (most recent call last):
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 386, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\bot.py", line 1653, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 303, in post
    **urlopen_kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 227, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError [Errno 2] No such file or directory
[ERROR   ] 14:27:33 updater:151 unhandled exception
Traceback (most recent call last):
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 148, in _thread_wrapper
    target(*args, **kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 274, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 386, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\bot.py", line 1653, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 303, in post
    **urlopen_kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 227, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError [Errno 2] No such file or directory
Exception in thread updater:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 148, in _thread_wrapper
    target(*args, **kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 274, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\ext\updater.py", line 386, in _bootstrap
    url=webhook_url, certificate=cert, allowed_updates=allowed_updates)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\bot.py", line 57, in decorator
    result = func(self, *args, **kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\bot.py", line 1653, in set_webhook
    result = self._request.post(url_, data, timeout=timeout)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 303, in post
    **urlopen_kwargs)
  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 227, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
NetworkError: urllib3 HTTPError [Errno 2] No such file or directory

[CRITICAL] 14:27:34 dispatcher:215 stopping due to exception in another thread

**OS and Version:**
 - OS: Windows 10
 - Deluge version: 1.3.15

**Additional context**
This is my first issue on github so sorry about any problems.

**Comment by noam09** [comment]
Hey @igorfrag, thanks for reporting this. It looks like we had something similar in #8 but maybe not exactly the same. 
I'll take a look at updating the `certifi` module in "includes", maybe that will help. I'll update here once I get a chance.

**Comment by igorfrag** [comment]
Thanks for the quick answer noam09, feel free to ask any info you might need.

**Comment by noam09** [comment]
Hey @igorfrag please try this build: https://github.com/noam09/deluge-telegramer/releases/download/v1.2.1-alpha/Telegramer-1.2.1.7_bugfix27_2-py2.7.egg
It contains the `certifi` package added to the `include` directory, maybe that will help with the issue. Please install the new `.egg` and restart Deluge afterwards before trying the plugin again. If it still fails or you encounter any other errors, please post them here.

**Comment by igorfrag** [comment]
Okay, so i removed the old version, installed the bugfix version, restarted deluge and then clicked test button. Still didn't work but different erros i guess. 

[ERROR   ] 03:42:06 __init__:58 Appending to sys.path: 'c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg/telegramer/include'
[ERROR   ] 03:42:07 __init__:58 Appending to sys.path: 'c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg/telegramer/include'

(deluge:3432): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(deluge:3432): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(deluge:3432): libglade-WARNING **: unknown attribute `swapped' for <signal>.
[ERROR   ] 03:42:07 __init__:58 Appending to sys.path: 'c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg/telegramer/include'
[ERROR   ] 03:42:07 updater:333 Error while bootstrap del webhook: urllib3 HTTPError [Errno 2] No such file or directory
[ERROR   ] 03:42:15 updater:333 Error while bootstrap del webhook: urllib3 HTTPError [Errno 2] No such file or directory
Unhandled error in Deferred:


Traceback (most recent call last):
  File "twisted/internet/_glibbase.py", line 375, in run

  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg\telegramer\gtkui.py", line 142, in on_button_test_clicked

  File "deluge\ui\client.py", line 504, in __call__

  File "deluge\ui\client.py", line 457, in call

--- <exception caught here> ---
  File "twisted/internet/defer.py", line 149, in maybeDeferred

  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg\telegramer\core.py", line 1154, in telegram_do_test

  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg\telegramer\include\telegram\bot.py", line 75, in decorator

  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg\telegramer\include\telegram\bot.py", line 100, in decorator

  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 340, in post

  File "c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg\telegramer\include\telegram\utils\request.py", line 240, in _request_wrapper

telegram.error.NetworkError: urllib3 HTTPError [Errno 2] No such file or directory
[ERROR   ] 03:42:25 updater:333 Error while bootstrap del webhook: urllib3 HTTPError [Errno 2] No such file or directory

**Comment by noam09** [comment]
Can you please make sure that you have debug logging enabled (`-L debug`), and then run the plugin again?
https://dev.deluge-torrent.org/wiki/Troubleshooting#WindowsSpecificLogging

**Comment by igorfrag** [comment]
Here it is: [Logs](https://github.com/noam09/deluge-telegramer/files/6681735/deluge.log)

**Comment by noam09** [comment]
Thank you, I'll have a look at the logs.
I think it would be best if you delete the last comment, and also generate a new token for your bot (https://t.me/Botfather), and send me any future files via email, since it looks like it may include some sensitive info (such as the bot token). You can find my email on my profile page. Thanks!

**Comment by noam09** [comment]
@igorfrag please try this version in debug mode:
https://github.com/noam09/deluge-telegramer/releases/download/v1.2.1-alpha/Telegramer-1.2_bugfix27_3-py2.7.egg
Please email the debug log to `noamgit {at] gmail.com`
The last version I asked you to try was the latest commit with the addition of `certifi`. Since that did not seem to work properly, I'd like to now try the latest stable commit (v1.2) with the addition of `certifi`, to rule out any breaking changes in the latest commit.

**Comment by igorfrag** [comment]
Still not working, sent the logs via email.

**Comment by noam09** [comment]
According to the logs it seems like the egg file loaded is `c:\users\user\appdata\roaming\deluge\plugins\telegramer-1.2.1.7_bugfix27_2-py2.7.egg`. It's possible Deluge isn't using the version from my last comment since the version number is "not newer". Before installing the last version, please try deleting or moving all versions of Telegramer from the plugins directory. Then restart Deluge, install the new version, and restart Deluge again to make sure. I know it seems like overkill but it's something I did often while developing, since I found it was the best way to get a clean slate.

**Comment by igorfrag** [comment]
Funny because i did exactly that and deluge even showed the correct version, i'll try again in some minutes.

![image](https://user-images.githubusercontent.com/58562585/122822217-2a445680-d2b4-11eb-82d2-647bf3449bf4.png)


Edit: Sent the logs on your email.

**Comment by igorfrag** [comment]
Issue solved on version 1.2-bugfix27-6, Thank you noah for helping me out via email, i'll close the issue.
