### ISSUE TITLE
[BUG] cant activate plugin on deluged 2.0.5

### ISSUE THREAD

**Issue by xzxzard** [noam09/deluge-telegramer#32]
**Describe the bug**
After install plugin egg it cant be activated in plugins menu

Message in log
```
22:08:49 [ERROR   ][deluge                        :59  ] NOTANERROR: Appending to sys.path: '/home/htpc/.config/deluge/plugins/Telegramer-1.2.1.7-py3.8.egg/telegramer/include'
22:08:49 [ERROR   ][deluge                        :87  ] 2022-04-05 22:08:49 # Telegramer: Import error - No module named 'urlparse'
Traceback (most recent call last):
  File "/home/htpc/.config/deluge/plugins/Telegramer-2.0.5.0-py3.10.egg/telegramer/core.py", line 68, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Bot, Update)
  File "<frozen zipimport>", line 259, in load_module
  File "/home/htpc/.config/deluge/plugins/Telegramer-1.2.1.7-py3.8.egg/telegramer/include/telegram/__init__.py", line 46, in <module>
    from .files.file import File
  File "<frozen zipimport>", line 259, in load_module
  File "/home/htpc/.config/deluge/plugins/Telegramer-1.2.1.7-py3.8.egg/telegramer/include/telegram/files/file.py", line 24, in <module>
    from urlparse import urlparse as urllib_parse
ModuleNotFoundError: No module named 'urlparse'

22:08:49 [ERROR   ][deluge.pluginmanagerbase      :155 ] Unable to instantiate plugin 'Telegramer' from '/home/htpc/.config/deluge/plugins/Telegramer-2.0.5.0-py3.10.egg'!
22:08:49 [ERROR   ][deluge.pluginmanagerbase      :1481] name 'CorePluginBase' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 150, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/home/htpc/.config/deluge/plugins/Telegramer-2.0.5.0-py3.10.egg/telegramer/__init__.py", line 65, in __init__
    from .core import Core as _plugin_cls
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/htpc/.config/deluge/plugins/Telegramer-2.0.5.0-py3.10.egg/telegramer/core.py", line 211, in <module>
    class Core(CorePluginBase):
NameError: name 'CorePluginBase' is not defined
```

deluged 2.0.5
libtorrent: 1.1.13.0
Python: 3.8.10
OS: Linux Ubuntu 20.04 focal

**Comment by noam09** [comment]
Hi @xzxzard, thanks for reporting this. Looking into it, I'll update this thread.

**Comment by noam09** [comment]
@xzxzard please try this `.egg` built with Python 3.8, see if it makes a difference:
https://github.com/noam09/deluge-telegramer/releases/download/v2.0.5.0/Telegramer-2.0.5.0-py3.8.egg

BTW it looks like your Deluge is trying to load `Telegramer-1.2.1.7-py3.8.egg`. Maybe try disabling it, or deleting the `.egg` file from `.config/deluge/plugins`.

**Comment by xzxzard** [comment]
Ty, now its works.
