### ISSUE TITLE
Can't save Category Settings

### ISSUE THREAD

**Issue by guiltyvictim** [noam09/deluge-telegramer#40]
**Describe the bug**
Unable to save Category settings via the Web UI

**To Reproduce**
1. Go to Preferences
2. Click on Telegramer
3. Scroll down to Categories
4. Add Categories
5. Click Apple and OK
6. Reload or Restart Deluge
7. Changes are not saved

**Expected behavior**
Categories should be saved

**Logs**
```
13:13:12 [ERROR   ][deluge.core.rpcserver              :1622] Exception calling RPC request: 'cat1'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/Telegramer.egg/telegramer/core.py", line 1111, in set_config
    self.config[key] != config[key]:
    ~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/config.py", line 235, in __getitem__
    return self.get_item(key)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/config.py", line 255, in get_item
    return self.__config[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'cat1'
13:13:12 [ERROR   ][deluge.ui.client           :1622] RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: telegramer.set_config({'cat1': 'test', 'dir1': '/test'})
--------------------------------------------------------------------------------
KeyError
'cat1': Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/Telegramer.egg/telegramer/core.py", line 1111, in set_config
    self.config[key] != config[key]:
    ~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/config.py", line 235, in __getitem__
    return self.get_item(key)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/config.py", line 255, in get_item
    return self.__config[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'cat1'

--------------------------------------------------------------------------------
13:13:12 [ERROR   ][deluge.ui.web.json_api     :1622] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: 'cat1'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/Telegramer.egg/telegramer/core.py", line 1111, in set_config
    self.config[key] != config[key]:
    ~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/config.py", line 235, in __getitem__
    return self.get_item(key)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deluge/config.py", line 255, in get_item
    return self.__config[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'cat1'
```

**OS and Version:**
 - OS: Centos 7
 - Deluge version: Deluge 2.1.1

**Additional context**
Installed via Docker. I've tried manually adding the json value from the logs into the "categories" key inside the Telegram.conf file but it still doesn't work after restart.

**Comment by noam09** [comment]
Hey @guiltyvictim, thanks for reporting and thank you for the logs.
I will look into this.

**Comment by noam09** [comment]
I may have found the issue, I hope to fix this soon. 🤞

**Comment by Prizmagnetic** [comment]
I think I have the same issue
OS: Linux Mint 21.1
Deluge 2.1.1
Python 3.10.6

I'm also only running deluged and accessing via deluge-web

**Comment by ArtemKiyashko** [comment]
@noam09 hey, any chance this to get fixed? :)
