### ISSUE TITLE
[BUG]  Can't get the plugin to work on Deluge 2.1.1

### ISSUE THREAD

**Issue by frasiercrane23** [noam09/deluge-telegramer#42]
**Describe the bug**
I can't seem to get the plugin to work. I get the errors on the log below.

**To Reproduce**
I put the .egg on my plugins folder and start deluge.

**Logs**
Telegramer: Import error - No module named 'certifi'
Traceback (most recent call last):
  File "/config/plugins/Telegramer-2.1.1.0-py3.10.egg/telegramer/core.py", line 71, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Bot, Update)
  File "/config/plugins/Telegramer-2.1.1.0-py3.10.egg/telegramer/include/telegram/__init__.py", line 175, in <module>
    from .bot import Bot
  File "/config/plugins/Telegramer-2.1.1.0-py3.10.egg/telegramer/include/telegram/bot.py", line 103, in <module>
    from telegram.utils.request import Request
  File "/config/plugins/Telegramer-2.1.1.0-py3.10.egg/telegramer/include/telegram/utils/request.py", line 33, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'

17:54:15 [ERROR   ][deluge.pluginmanagerbase         :153 ] Unable to instantiate plugin 'Telegramer' from '/config/plugins/Telegramer-2.1.1.0-py3.10.egg'!
17:54:15 [ERROR   ][deluge.pluginmanagerbase         :1512] name 'CorePluginBase' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/Telegramer-2.1.1.0-py3.10.egg/telegramer/__init__.py", line 65, in __init__
    from .core import Core as _plugin_cls
  File "/config/plugins/Telegramer-2.1.1.0-py3.10.egg/telegramer/core.py", line 214, in <module>
    class Core(CorePluginBase):

**OS and Version:**
 - OS: Linux
 - Deluge version: 2.1.1
`deluge --version` or `deluged --version`

Thanks

**Comment by noam09** [comment]
Hey @frasiercrane23, is Deluge running locally on the host or in a Docker container? In either case, which Python version is installed (`python --version`)? Can you try running `pip install certifi` ?

**Comment by frasiercrane23** [comment]
Hello! Thanks for your help. 

Deluge is in a docker container. I'm using binhex delugevpn.

python version is: 3.10.9

The command pip install certifi returned the following:

Downloading/unpacking certifi
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement certifi
Cleaning up...
No distributions at all found for certifi

Thank you

**Comment by ionedji** [comment]
had the same issue, resolved it by installing another docker from [linuxserver](https://github.com/linuxserver/docker-deluge) and plugin installed successfully. Seems something is wrong in binhex docker

**Comment by noam09** [comment]
Hey @frasiercrane23 I missed your last comment, sorry about that. I think I may need to update the requests/urllib included library to fix this, or maybe just ignore certifi for certain Python versions. Hopefully I will have time to fix this soon.
Until then, maybe you can try out another dockerized version of Deluge like @ionedji suggested.

**Comment by frasiercrane23** [comment]
Hi guys,

Thanks for the replies. Changing to another Deluge docker is out of the question at the moment. It's not a dealbreaker for me. I'll be happy to test it once you find the time to update the plugin. Thanks!

**Comment by elizhyu** [comment]
Same issue here with
- deluge version ```2.1.1```
  - ```docker``` installation
  - package from ```linuxserver```
- plugin version ```2.1.1.0```
- python version ```3.11```

**Comment by noam09** [comment]
@frasiercrane23 @elizhyu please try out the .egg in this pre-release:
https://github.com/noam09/deluge-telegramer/releases/tag/2.1.1.1-beta1
I've packaged the latest `certifi` into the egg, let's see if that resolves anything.
Sorry it took so long.

**Comment by Ssshafi** [comment]
Same issue for me : 

- Deluge  : 2.1.1 on docker with linuxserver image.
- Python version : 3.11.3
- Plugin version : 2.1.1.1-beta1

> [custom-init] No custom files found, skipping...
01:30:52 [ERROR   ][deluge                        :1622] NOTANERROR: Appending to sys.path: '/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include'
/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/utils/request.py:54: UserWarning: python-telegram-bot wasn't properly installed. Please refer to README.rst on how to properly install.
01:30:52 [ERROR   ][telegramer.core               :1622] 2023-05-27 01:30:52 # Telegramer: Import error - No module named 'urllib3.contrib.appengine'
Traceback (most recent call last):
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/utils/request.py", line 36, in <module>
    import telegram.vendor.ptb_urllib3.urllib3 as urllib3
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/vendor/ptb_urllib3/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/vendor/ptb_urllib3/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/vendor/ptb_urllib3/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name 'ssl_match_hostname' from partially initialized module 'telegram.vendor.ptb_urllib3.urllib3.packages' (most likely due to a circular import) (/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/vendor/ptb_urllib3/urllib3/packages/__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/core.py", line 71, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Bot, Update)
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/__init__.py", line 175, in <module>
    from .bot import Bot
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/bot.py", line 103, in <module>
    from telegram.utils.request import Request
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/include/telegram/utils/request.py", line 44, in <module>
    import urllib3.contrib.appengine as appengine  # type: ignore[no-redef]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'urllib3.contrib.appengine'
01:30:52 [ERROR   ][deluge.pluginmanagerbase      :1622] Unable to instantiate plugin 'Telegramer' from '/config/plugins/Telegramer-2.1.1.1-py3.11.egg'!
01:30:52 [ERROR   ][deluge.pluginmanagerbase      :1622] name 'CorePluginBase' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/__init__.py", line 65, in __init__
    from .core import Core as _plugin_cls
  File "/config/plugins/Telegramer-2.1.1.1-py3.11.egg/telegramer/core.py", line 214, in <module>
    class Core(CorePluginBase):
               ^^^^^^^^^^^^^^
NameError: name 'CorePluginBase' is not defined
[ls.io-init] done.

**Comment by noam09** [comment]
@Ssshafi please try out one of these instead:
- https://github.com/noam09/deluge-telegramer/releases/download/2.1.1.1-beta1/Telegramer-2.1.1.1-py3.11.egg

If the above doesn't work, try this one:
- https://github.com/noam09/deluge-telegramer/releases/download/2.1.1.1-beta1/Telegramer-2.1.1.2-py3.11.egg

**Comment by Ssshafi** [comment]
Previous post was done with [2.1.1.1-beta1/Telegramer-2.1.1.1-py3.11.egg]

I've tried [2.1.1.1-beta1/Telegramer-2.1.1.2-py3.11.egg] two days ago with no luck.
Today I retry 2.1.1.2 and now it's good....

Thank you

**Comment by noam09** [comment]
@Ssshafi great news! Just to clarify, the version that is working for you is:
```
f54147e15cee2ca9ef3b0483fda4ab2d  Telegramer-2.1.1.2-py3.11.egg
```
@frasiercrane23 @elizhyu maybe this will also work for you

**Comment by frasiercrane23** [comment]
Hello! Sorry for the late reply.  Telegramer-2.1.1.2-py3.11.egg seems to be working! :) Thanks!
