### ISSUE TITLE
[BUG] Chat not found error on deluge docker

### ISSUE THREAD

**Issue by ionedji** [noam09/deluge-telegramer#44]
**Describe the bug**
Unable to make plugin connect to telegram bot

**To Reproduce**
1. Install [linuxserver deluge docker](https://github.com/linuxserver/docker-deluge)
2. Add .egg to plugins folder
3. Add telegram user id and token
4. "/start" telegram bot you have created
5. Run test in the plugin 

**Logs**
`2023-03-29T16:03:46.821620743Z 22:03:46 [DEBUG   ][deluge.ui.web.json_api     :1622] json-request: b'{"method":"telegramer.telegram_do_test","params":[],"id":26}'
2023-03-29T16:03:46.823050059Z 22:03:46 [DEBUG   ][deluge.core.rpcserver              :1622] RPC dispatch telegramer.telegram_do_test
2023-03-29T16:03:46.823102376Z 22:03:46 [INFO    ][telegramer.core                    :1622] 2023-03-29 22:03:46 # Telegramer: Send test
2023-03-29T16:03:46.823182163Z 22:03:46 [DEBUG   ][telegram.bot                       :1622] Entering: send_sticker
2023-03-29T16:03:46.824501527Z 22:03:46 [DEBUG   ][urllib3.connectionpool             :1622] Starting new HTTPS connection (2): api.telegram.org:443
2023-03-29T16:03:46.859571951Z 22:03:46 [DEBUG   ][deluge.ui.web.json_api     :1622] json-request: b'{"method":"web.update_ui","params":[["queue","name","total_wanted","state","progress","num_seeds","total_seeds","num_peers","total_peers","download_payload_rate","upload_payload_rate","eta","ratio","distributed_copies","is_auto_managed","time_added","tracker_host","download_location","last_seen_complete","total_done","total_uploaded","max_download_speed","max_upload_speed","seeds_peers_ratio","total_remaining","completed_time","time_since_transfer","label"],{}],"id":27}'
2023-03-29T16:03:47.187658429Z 22:03:47 [DEBUG   ][urllib3.connectionpool             :1622] https://api.telegram.org:443 "POST /bot6250350122:AAGuGonH6QgxG5F-5AmoNYr8U9wgg_ZpTFU/sendSticker HTTP/1.1" 400 73
2023-03-29T16:03:47.198700493Z 22:03:47 [WARNING ][deluge.core.rpcserver              :1622] An exception occurred while sending RPC_ERROR to client. Wrapping it and resending. Error to send(causing exception goes next):
2023-03-29T16:03:47.198730775Z Traceback (most recent call last):
2023-03-29T16:03:47.198741055Z   File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
2023-03-29T16:03:47.198749825Z     ret = self.factory.methods[method](*args, **kwargs)
2023-03-29T16:03:47.198758078Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.198766840Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/core.py", line 1160, in telegram_do_test
2023-03-29T16:03:47.198775863Z     self.bot.sendSticker(self.config['telegram_user'],
2023-03-29T16:03:47.198784107Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 130, in decorator
2023-03-29T16:03:47.198792547Z     result = func(*args, **kwargs)
2023-03-29T16:03:47.198808552Z              ^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.198833470Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 1044, in send_sticker
2023-03-29T16:03:47.198842328Z     return self._message(  # type: ignore[return-value]
2023-03-29T16:03:47.198849948Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.198857453Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 336, in _message
2023-03-29T16:03:47.198865369Z     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2023-03-29T16:03:47.198873263Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.198881040Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 295, in _post
2023-03-29T16:03:47.198888890Z     return self.request.post(
2023-03-29T16:03:47.198896414Z            ^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.198903975Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 361, in post
2023-03-29T16:03:47.198911935Z     result = self._request_wrapper(
2023-03-29T16:03:47.198919486Z              ^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.198927142Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 279, in _request_wrapper
2023-03-29T16:03:47.198935152Z     raise BadRequest(message)
2023-03-29T16:03:47.198942606Z telegram.error.BadRequest: Chat not found
2023-03-29T16:03:47.198950164Z 
2023-03-29T16:03:47.201884331Z 22:03:47 [ERROR   ][deluge.core.rpcserver              :1622] Exception calling RPC request: Chat not found
2023-03-29T16:03:47.201908492Z Traceback (most recent call last):
2023-03-29T16:03:47.201917969Z   File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
2023-03-29T16:03:47.201925672Z     ret = self.factory.methods[method](*args, **kwargs)
2023-03-29T16:03:47.201932748Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.201940251Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/core.py", line 1160, in telegram_do_test
2023-03-29T16:03:47.201952194Z     self.bot.sendSticker(self.config['telegram_user'],
2023-03-29T16:03:47.201963057Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 130, in decorator
2023-03-29T16:03:47.201970844Z     result = func(*args, **kwargs)
2023-03-29T16:03:47.201978455Z              ^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.201990220Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 1044, in send_sticker
2023-03-29T16:03:47.201998356Z     return self._message(  # type: ignore[return-value]
2023-03-29T16:03:47.202005538Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.202012419Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 336, in _message
2023-03-29T16:03:47.202019745Z     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2023-03-29T16:03:47.202026831Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.202035503Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 295, in _post
2023-03-29T16:03:47.202046651Z     return self.request.post(
2023-03-29T16:03:47.202058996Z            ^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.202069494Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 361, in post
2023-03-29T16:03:47.202082153Z     result = self._request_wrapper(
2023-03-29T16:03:47.202093634Z              ^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.202105304Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 279, in _request_wrapper
2023-03-29T16:03:47.202117973Z     raise BadRequest(message)
2023-03-29T16:03:47.202129553Z telegram.error.BadRequest: Chat not found
2023-03-29T16:03:47.202758832Z 22:03:47 [DEBUG   ][deluge.core.alertmanager           :1622] Alerts queued: 1
2023-03-29T16:03:47.202953116Z 22:03:47 [DEBUG   ][deluge.core.alertmanager           :1622] session_stats_alert: session stats (291 values): 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 204, 0, 0, 88, 2, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2193, 0, 2193, 2193, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3360, 0, 0, 0, 2520, 0, 0, 0, 90, 0, 120, 0, 27453, 12515, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 8, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0
2023-03-29T16:03:47.202990626Z 22:03:47 [DEBUG   ][deluge.core.alertmanager           :1622] Handling alert: session_stats_alert
2023-03-29T16:03:47.203110651Z 22:03:47 [ERROR   ][deluge.ui.client           :1622] RPCError Message Received!
2023-03-29T16:03:47.203129880Z --------------------------------------------------------------------------------
2023-03-29T16:03:47.203138734Z RPCRequest: telegramer.telegram_do_test()
2023-03-29T16:03:47.203146211Z --------------------------------------------------------------------------------
2023-03-29T16:03:47.203153561Z BadRequest
2023-03-29T16:03:47.203160390Z Chat not found: Traceback (most recent call last):
2023-03-29T16:03:47.203167395Z   File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
2023-03-29T16:03:47.203174524Z     ret = self.factory.methods[method](*args, **kwargs)
2023-03-29T16:03:47.203181312Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203188257Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/core.py", line 1160, in telegram_do_test
2023-03-29T16:03:47.203195476Z     self.bot.sendSticker(self.config['telegram_user'],
2023-03-29T16:03:47.203202376Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 130, in decorator
2023-03-29T16:03:47.203209489Z     result = func(*args, **kwargs)
2023-03-29T16:03:47.203216208Z              ^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203223039Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 1044, in send_sticker
2023-03-29T16:03:47.203230261Z     return self._message(  # type: ignore[return-value]
2023-03-29T16:03:47.203244740Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203251895Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 336, in _message
2023-03-29T16:03:47.203259105Z     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2023-03-29T16:03:47.203266047Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203272923Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 295, in _post
2023-03-29T16:03:47.203280156Z     return self.request.post(
2023-03-29T16:03:47.203287046Z            ^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203293834Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 361, in post
2023-03-29T16:03:47.203315718Z     result = self._request_wrapper(
2023-03-29T16:03:47.203323841Z              ^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203330946Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 279, in _request_wrapper
2023-03-29T16:03:47.203338198Z     raise BadRequest(message)
2023-03-29T16:03:47.203344833Z telegram.error.BadRequest: Chat not found
2023-03-29T16:03:47.203358127Z 
2023-03-29T16:03:47.203364892Z --------------------------------------------------------------------------------
2023-03-29T16:03:47.203376501Z 22:03:47 [DEBUG   ][deluge.core.rpcserver              :1622] RPC dispatch core.get_torrents_status
2023-03-29T16:03:47.203384064Z 22:03:47 [ERROR   ][deluge.ui.web.json_api     :1622] [Failure instance: Traceback (failure with no frames): <class 'deluge.error.WrappedException'>: Chat not found
2023-03-29T16:03:47.203391716Z Traceback (most recent call last):
2023-03-29T16:03:47.203398626Z   File "/usr/lib/python3.11/site-packages/deluge/core/rpcserver.py", line 334, in dispatch
2023-03-29T16:03:47.203405633Z     ret = self.factory.methods[method](*args, **kwargs)
2023-03-29T16:03:47.203412357Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203419184Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/core.py", line 1160, in telegram_do_test
2023-03-29T16:03:47.203426128Z     self.bot.sendSticker(self.config['telegram_user'],
2023-03-29T16:03:47.203432711Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 130, in decorator
2023-03-29T16:03:47.203439632Z     result = func(*args, **kwargs)
2023-03-29T16:03:47.203446248Z              ^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203452743Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 1044, in send_sticker
2023-03-29T16:03:47.203459701Z     return self._message(  # type: ignore[return-value]
2023-03-29T16:03:47.203466456Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203473153Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 336, in _message
2023-03-29T16:03:47.203480192Z     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2023-03-29T16:03:47.203486878Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203493672Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/bot.py", line 295, in _post
2023-03-29T16:03:47.203507150Z     return self.request.post(
2023-03-29T16:03:47.203514217Z            ^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203520965Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 361, in post
2023-03-29T16:03:47.203536534Z     result = self._request_wrapper(
2023-03-29T16:03:47.203544549Z              ^^^^^^^^^^^^^^^^^^^^^^
2023-03-29T16:03:47.203551564Z   File "/config/plugins/Telegramer-2.1.1.0-py3.11.egg/telegramer/include/telegram/utils/request.py", line 279, in _request_wrapper
2023-03-29T16:03:47.203559109Z     raise BadRequest(message)
2023-03-29T16:03:47.203565814Z telegram.error.BadRequest: Chat not found
`

**OS and Version:**
 - Docker [linuxserver deluge docker](https://github.com/linuxserver/docker-deluge)
 - OS: ghcr.io/linuxserver/baseimage-alpine:edge
 - Deluge version: 2.1.1

**Additional context**
It seems that plugin unable to find the bot chat that I created, but I definitely input the name of the bot right and started it before 'Test' run. Also bot token added to plugin.

Thought that maybe plugin unable to reach internet while it`s in docker container? But don't know if it is the reason or not.

**Comment by noam09** [comment]
Hi @ionedji! First of all, please notice that your bot token is showing up in the logs you posted. I would suggest generating a new token for your bot and using the new token instead - you can do that with Botfather.
Next, let's make sure the chat ID you are using is defined correctly. How did you determine the chat ID? Is it a private chat or group chat? Did you use `@myidbot` to retrieve it?

**Comment by ionedji** [comment]
> Hi @ionedji! First of all, please notice that your bot token is showing up in the logs you posted. I would suggest generating a new token for your bot and using the new token instead - you can do that with Botfather. Next, let's make sure the chat ID you are using is defined correctly. How did you determine the chat ID? Is it a private chat or group chat? Did you use `@myidbot` to retrieve it?

Thank you very much, I`m an idiot, didn't get the instructions right and have inputed bot name instead of bot ID. I thought that /getid command should work in created bot directly. And only know I get that you need to send message to additional bot with this name: `@myidbot`. Now it`s working as it should.
