### ISSUE TITLE
[BUG] Telegramer does not start after updating deluge

### ISSUE THREAD

**Issue by Lukki4** [noam09/deluge-telegramer#48]
**Describe the bug**
Telegramer does not start after updating deluge

**Screenshots**
![No work](https://github.com/noam09/deluge-telegramer/assets/112572763/5d3bcd4c-2c09-4281-a8fa-48aa40dd4a72)

**Logs**
09:14:18 [ERROR   ][deluge.pluginmanagerbase      :1672] Unable to instantiate plugin 'Telegramer' from '/config/plugins/Telegramer-2.1.1.2-py3.11.egg'!
09:14:18 [ERROR   ][deluge.pluginmanagerbase      :1672] The 'Telegramer' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/Telegramer-2.1.1.2-py3.11.egg/telegramer/__init__.py", line 64, in __init__
    load_libs()
  File "/config/plugins/Telegramer-2.1.1.2-py3.11.egg/telegramer/__init__.py", line 53, in load_libs
    egg = pkg_resources.require("Telegramer")[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 937, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 839, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Telegramer' distribution was not found and is required by the application

- Windows users, see: https://dev.deluge-torrent.org/wiki/Troubleshooting#WindowsSpecificLogging

**OS and Version:**
OS: Linux
Deluge version: [e.g. 2.1.1]
deluge --version or deluged --version

**Comment by t0fum4n** [comment]
Here to say that I have the same issue. I think it has something to do with the python versioning, but I built an egg from source for 3.12 and it still didn't work.

**Comment by crypticviper** [comment]
I too cannot get the plugin to work with latest version of deluge. I don't see any errors logged. I manually installed the plugin but unable to enable it from the GUI. It's probably something to do with python version but I am not sure.

**Comment by ssheytanov** [comment]
Same issue for me on windows 11 - ![Image](https://i.imgur.com/qevcPod.png)

**Comment by jandolejs** [comment]
Hi, same for me, 
docker image: lscr.io/linuxserver/deluge 2.1.1
uploaded plugin to: /config/plugins/Telegramer-2.1.1.2-py3.11.egg
after trying to eable it in GUI, same error occured

**Comment by noam09** [comment]
Sorry it took me so long to find the time for this. 

Please try [this build](https://github.com/noam09/deluge-telegramer/releases/download/2.1.1.3/Telegramer-2.1.1.3-py3.12.egg) from [this release](https://github.com/noam09/deluge-telegramer/releases/tag/2.1.1.3). If the WebUI plugin upload doesn't work right, you can try replacing the existing `.egg` file in the `plugins` directory with this new one.

Please let me know if it works or not.

**Comment by crypticviper** [comment]
@noam09 thanks.

I installed plugin manually (coped to plugins directory) restarted deluge. I can see the plugin under plugins tab. However, I select and then apply/ok or close, it doesn't stay enabled. I do not see any errors in deluge container logs.

I am running binhex-deluge docker container on Unraid 6.12.13

**Edit**: Python version on deluge container is 3.12.4 so I used  Telegramer-2.1.1.3-py3.12.egg.

**Comment by noam09** [comment]
@crypticviper when you click on the plugin name, what version of the plugin does it show as installed?
At this point, assuming the checkbox is unchecked (plugin not enabled), what logs does the container show when you check the box to enable the plugin?

**Comment by crypticviper** [comment]
Installed plugin info from deluge UI:

![image](https://github.com/user-attachments/assets/7be43798-67bc-465d-adef-008f1f94b404)

Unfortunately no useful logs are present in the container logs. I have debug logs enabled for the container. I have restarted the container several times to no avail. Also tried all kinds of browsers to see if that is an issue but doesn't seem like.

**Comment by noam09** [comment]
@crypticviper any logs at all containing the word "telegram"? Please post them here if so.

**Comment by crypticviper** [comment]
Below logs are spewed out every minute and I don't think they have anything to do with this plugin

> 2024-09-11 13:03:22,971 DEBG 'watchdog-script' stdout output:
[debug] Checking we can resolve name 'www.google.com' to address...
2024-09-11 13:03:23,013 DEBG 'watchdog-script' stdout output:
[debug] DNS operational, we can resolve name 'www.google.com' to address 'XXX.XXX.XXX.XXX'
[debug] Waiting for iptables chain policies to be in place...
2024-09-11 13:03:23,018 DEBG 'watchdog-script' stdout output:
[debug] iptables chain policies are in place
2024-09-11 13:03:23,024 DEBG 'watchdog-script' stdout output:
[debug] VPN IP is XXX.XXX.XXX.XXX
[debug] Deluge IP is XXX.XXX.XXX.XXX

**Comment by noam09** [comment]
@crypticviper these seem to be related to DelugeVPN. Are there zero mentions of "telegram" in the logs since the container startup? Is everything else working fine in Deluge?

**Comment by crypticviper** [comment]
@noam09 Nope, no telegramer related logs. Everything else just seems to work perfectly. I use a deluge container that has VPN stuff built in, not sure if that creates any issue? But there are absolutely no logs related to the plugin. All I see are above logs repeatedly. Enabling other plugins (which came with deluge) seems to work fine. I have not tried manual installation of any other plugin. I will probably check that and see if manual installation of plugins even works.

**Comment by noam09** [comment]
@crypticviper maybe something with the VPN stuff is interfering with the plugin? Has it worked fine in the past?

**Comment by crypticviper** [comment]
> @crypticviper maybe something with the VPN stuff is interfering with the plugin? Has it worked fine in the past?

Sorry for late response. I finally found some logs hiding in deluged.log file. Below is what it looks like.

> 17:45:56 [ERROR   ][deluge                        :1672] NOTANERROR: Appending to sys.path: '/config/plugins/Telegramer-2.1.1.3-py3.12.egg/telegramer/include'
17:45:56 [ERROR   ][telegramer.core               :1672] 2024-11-24 17:45:56 # Telegramer: Import error - No module named 'certifi'
Traceback (most recent call last):
  File "/config/plugins/Telegramer-2.1.1.3-py3.12.egg/telegramer/core.py", line 71, in <module>
    from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Bot, Update)
  File "/config/plugins/Telegramer-2.1.1.3-py3.12.egg/telegramer/include/telegram/__init__.py", line 175, in <module>
    from .bot import Bot
  File "/config/plugins/Telegramer-2.1.1.3-py3.12.egg/telegramer/include/telegram/bot.py", line 103, in <module>
    from telegram.utils.request import Request
  File "/config/plugins/Telegramer-2.1.1.3-py3.12.egg/telegramer/include/telegram/utils/request.py", line 33, in <module>
    import certifi
ModuleNotFoundError: No module named 'certifi'

**Comment by crypticviper** [comment]
Ok update.

I manually installed the following packages in the docker container:

- certifi
- requests
- six

(and may be some more).

Now the plugin enabling works and it stays enabled. I also get the telegramer tab where I can configure the plugin.

I guess next step is to let the container maintainer know about this so that the container comes with these packages pre-installed.
